import code-lint workflow job
bfenetworks/bfe pull request #1037
Opened 2022-03-23 14:11 UTC by kwanhur

* upgrade actions/checkout@v3
* import staticcheck action@v1.0.0
* enable go vet

2022-04-11 12:09 UTC, kwanhur commented
cc @iyangsj @mileszhang2016

2022-04-28 09:02 UTC, iyangsj commented on bfe_balance/bal_slb/bal_rr.go
> +//lint:file-ignore U1000 Ignore field is unused
这条规则建议统一忽略（或修复）
U1000 Ignore func is unused

2022-04-28 09:02 UTC, iyangsj requested changes
见批注

2022-04-29 13:54 UTC, kwanhur commented on bfe_balance/bal_slb/bal_rr.go
> +//lint:file-ignore U1000 Ignore field is unused
已经统一在 `staticcheck.conf` 添加忽略规则 `"-U1000"`

2022-05-28 00:34 UTC, merged