fix some unreachable code
bfenetworks/bfe pull request #1068
Opened 2022-08-10 08:53 UTC by Abirdcfly

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

see https://go.dev/play/p/8fS-lKgH7Ze for example:
```go
package main

import (
	"fmt"
	"testing"
	"time"
)

func TestA(t *testing.T) {
	errc := make(chan error, 1)
	donec := make(chan bool)

	go func() {
		defer close(donec)
		time.Sleep(time.Second)
		// time.Sleep(10 * time.Second) // or you want test with timeout.
	}()

	select {
	case <-donec:
		fmt.Println("just return")
		return
	case <-time.After(5 * time.Second):
		t.Fatal("timeout")
	}
	fmt.Println("cant reach!!!")
	e := fmt.Errorf("err one")
	errc <- e
	select {
	case err := <-errc:
		if err != nil {
			t.Fatalf("Error in handler: %v", err)
		}
	case <-time.After(2 * time.Second):
		t.Error("timeout waiting for handler to finish")
	}
}

/* 
// Output:
=== RUN   TestA
just return
--- PASS: TestA (1.00s)
PASS

Program exited.

// Output when uncommenting line 16 and letting the program time out:
=== RUN   TestA
    prog.go:24: timeout
--- FAIL: TestA (5.00s)
FAIL

Program exited.
*/

```

2022-08-11 15:12 UTC, kwanhur commented
Maybe a little change per pull request will be better.

2022-08-13 04:03 UTC, iyangsj requested changes

2022-08-15 07:02 UTC, Abirdcfly commented on bfe_basic/condition/primitive_test.go
>  		t.Fatalf("Fetch(): %v", err)
好的。
- [当前PR](https://github.com/bfenetworks/bfe/pull/1068) 包含 1、4处删除提交。
- [#1069](https://github.com/bfenetworks/bfe/pull/1069) 包含2、3处改动和可能的测试用例修复。

2022-08-15 07:02 UTC, Abirdcfly commented on bfe_spdy/server_test.go
> +		errc := make(chan error, defaultMaxStreams)
Done

2022-08-15 07:03 UTC, Abirdcfly commented on bfe_http2/server_test.go
> +		errc := make(chan error, 1)
Done

2022-08-22 04:37 UTC, iyangsj approved these changes

2022-08-22 04:37 UTC, merged

2022-08-22 04:38 UTC, iyangsj commented
@Abirdcfly  请回复微信号或添加微信好友 iyangsj, 将邀请加入开源BFE开发者群方便交流