add zh_cn doc for mod_tcp_keepalive
bfenetworks/bfe pull request #911
Opened 2021-12-19 07:30 UTC by dblate

Signed-off-by: yuhui06 <yuhui06@baidu.com>

2021-12-19 07:57 UTC, dblate commented
include en_us doc

2021-12-20 02:33 UTC, mileszhang2016 requested changes

2021-12-20 02:33 UTC, mileszhang2016 commented on docs/zh_cn/modules/mod_tcp_keepalive/mod_tcp_keepalive.md
> +| Config{v} | Array<br>产品线下规则列表 |
产品线下规则列表 => 产品线的规则列表

2021-12-20 02:33 UTC, mileszhang2016 commented on docs/en_us/modules/mod_tcp_keepalive/mod_tcp_keepalive.md
> +| Config{v}[].VipConf | Array<br>The IP list to set the keepalive message strategy  |
=> 
The list of virtual IPs to set the keepalive message strategy

2021-12-20 02:33 UTC, mileszhang2016 commented on docs/zh_cn/modules/mod_tcp_keepalive/mod_tcp_keepalive.md
> +| Config{v}[].VipConf | Array<br>需要配置的IP数组，数组中的IP共用以下同一套策略 |
需要配置的VIP（Virtual IP）数组，数组中的VIP共用以下同一套策略

2021-12-20 06:15 UTC, merged