typo: fix annotations of bfe_net bfe_proxy
bfenetworks/bfe pull request #988
Opened 2022-01-30 06:31 UTC by kwanhur

2022-01-30 06:42 UTC, liu-song commented
https://github.com/crate-ci/typos，@kwanhur ，这个工具比较厉害，可以检查一些typos的拼写错误，可以添加在自己fork 的仓库中的workflow中开启action来检查有哪些拼写场景下typos 的错误，；）

2022-01-30 14:54 UTC, mileszhang2016 requested changes

2022-01-30 14:54 UTC, mileszhang2016 commented on bfe_proxy/common.go
> +// ProxyState State for Proxy
// ProxyState is State for Proxy

2022-01-31 02:26 UTC, kwanhur commented
> [https://github.com/crate-ci/typos，](https://github.com/crate-ci/typos%EF%BC%8C) @kwanhur ，这个工具比较厉害，可以检查一些typos的拼写错误，可以添加在自己fork 的仓库中的workflow中开启action来检查有哪些拼写场景下typos 的错误，可以在统一修改之后合并成一个pr提交上来；）

ok, but too many modifications in one pull request, isn't friendly enough.

2022-01-31 05:44 UTC, merged